import textwrap
import unittest

from sqlift_poc import parse_sql, to_pandas_code


def _normalize(code: str) -> list[str]:
    """
    Make string comparisons resilient to trivial whitespace differences.
    - Strips leading/trailing whitespace
    - Drops empty lines
    - Right-strips each line
    """
    return [ln.rstrip() for ln in code.strip().splitlines() if ln.strip()]


class SQLiftTests(unittest.TestCase):
    def assertCodeEqual(self, generated: str, expected: str):
        self.assertEqual(_normalize(generated), _normalize(expected))

    def test_parse_sql_handles_join_alias(self):
        sql = textwrap.dedent(
            """
            SELECT c.customer_id, o.amount
            FROM orders o
            JOIN customers c ON o.customer_id = c.customer_id
            """
        )

        query = parse_sql(sql)

        self.assertEqual(
            query.joins,
            [{"table": "customers", "left": "o.customer_id", "right": "c.customer_id"}],
        )

    def test_to_pandas_code_groupby_with_aggregate_and_alias(self):
        sql = textwrap.dedent(
            """
            SELECT c.customer_id, SUM(o.amount) AS total_amount
            FROM orders o
            JOIN customers c ON o.customer_id = c.customer_id
            WHERE o.status = 'PAID'
            GROUP BY c.customer_id
            ORDER BY SUM(o.amount) DESC
            LIMIT 100
            """
        )

        code = to_pandas_code(
            parse_sql(sql), {"orders": "df_orders", "customers": "df_customers"}
        )

        expected = textwrap.dedent(
            """
            # Generated by SQLift PoC
            df = df_orders.copy()
            df = df.merge(df_customers, on='customer_id', how='inner')
            df = df.query("status == 'PAID'")
            df = df.groupby(['customer_id'], as_index=False).agg({'total_amount': ('amount', 'sum')})
            df = df.sort_values(by='total_amount', ascending=False)
            df = df.head(100)
            """
        ).strip()

        self.assertCodeEqual(code, expected)

    def test_to_pandas_code_groupby_without_aggregate(self):
        sql = textwrap.dedent(
            """
            SELECT c.customer_id
            FROM customers c
            GROUP BY c.customer_id
            ORDER BY c.customer_id
            """
        )

        code = to_pandas_code(parse_sql(sql), {"customers": "df_customers"})

        # Fixed: ensure we project the selected column and not keep extra columns around.
        expected = textwrap.dedent(
            """
            # Generated by SQLift PoC
            df = df_customers.copy()
            df = df.drop_duplicates(subset=['customer_id'])
            df = df[['customer_id']]
            df = df.sort_values(by='customer_id', ascending=True)
            """
        ).strip()

        self.assertCodeEqual(code, expected)

    def test_to_pandas_code_where_clause_normalization(self):
        sql = textwrap.dedent(
            """
            SELECT o.status
            FROM orders o
            WHERE o.status = 'PAID' AND o.kind <> "X"
            ORDER BY o.status
            """
        )

        code = to_pandas_code(parse_sql(sql), {"orders": "df_orders"})

        expected = textwrap.dedent(
            """
            # Generated by SQLift PoC
            df = df_orders.copy()
            df = df.query('status == \\'PAID\\' and kind != "X"')
            df = df[['status']]
            df = df.sort_values(by='status', ascending=True)
            """
        ).strip()

        self.assertCodeEqual(code, expected)

    def test_to_pandas_code_groupby_with_having_and_distinct(self):
        sql = textwrap.dedent(
            """
            SELECT
                c.customer_id,
                c.customer_name,
                SUM(o.amount) AS total_spent,
                AVG(o.amount) AS avg_order,
                COUNT(DISTINCT o.order_id) AS num_orders
            FROM customers AS c
            INNER JOIN orders AS o
                ON c.customer_id = o.customer_id
            WHERE o.order_date BETWEEN '01JAN2024'd AND '31MAR2024'd
                  AND o.status = 'Completed'
            GROUP BY c.customer_id, c.customer_name
            HAVING SUM(o.amount) > 1000
            ORDER BY total_spent DESC
            LIMIT 5;
            """
        )

        code = to_pandas_code(
            parse_sql(sql),
            {"customers": "df_customers", "orders": "df_orders"},
        )

        expected = textwrap.dedent(
            """
            # Generated by SQLift PoC
            df = df_customers.copy()
            df = df.merge(df_orders, on='customer_id', how='inner')
            df = df.query("(order_date >= '2024-01-01') and (order_date <= '2024-03-31') and status == 'Completed'")
            df = df.groupby(['customer_id', 'customer_name'], as_index=False).agg({'total_spent': ('amount', 'sum'), 'avg_order': ('amount', 'mean'), 'num_orders': ('order_id', 'nunique')})
            df = df.query('total_spent > 1000')
            df = df.sort_values(by='total_spent', ascending=False)
            df = df.head(5)
            """
        ).strip()

        self.assertCodeEqual(code, expected)

    def test_to_pandas_code_where_clause_in_operator(self):
        sql = textwrap.dedent(
            """
            SELECT p.product_id
            FROM products p
            WHERE p.region IN ('Berlin', 'Munich', 'Hamburg')
            """
        )

        code = to_pandas_code(parse_sql(sql), {"products": "products"})

        expected = textwrap.dedent(
            """
            # Generated by SQLift PoC
            df = products.copy()
            df = df.query("region in ['Berlin', 'Munich', 'Hamburg']")
            df = df[['product_id']]
            """
        ).strip()

        self.assertCodeEqual(code, expected)

    def test_to_pandas_code_count_star_shortcut(self):
        sql = textwrap.dedent(
            """
            SELECT customer_id, COUNT(*) AS num_orders
            FROM orders
            WHERE order_date >= '2025-01-01'
            GROUP BY customer_id
            HAVING COUNT(*) > 5
            ORDER BY num_orders DESC
            """
        )

        code = to_pandas_code(parse_sql(sql), {"orders": "orders"})

        expected = textwrap.dedent(
            """
            # Generated by SQLift PoC
            df = orders.copy()
            df = df.query("order_date >= '2025-01-01'")
            df = df.groupby('customer_id', as_index=False).size().rename(columns={'size': 'num_orders'})
            df = df.query('num_orders > 5')
            df = df.sort_values(by='num_orders', ascending=False)
            """
        ).strip()

        self.assertCodeEqual(code, expected)


if __name__ == "__main__":
    unittest.main()
